module.exports = {
  module: 'react-ui-tree',
  tree_item_id: 12,
  children: [{
    module: 'dist',
    tree_item_id: 134,
    collapsed: true,
    children: [{
      module: 'node.js',
      tree_item_id: 134534,
      leaf: true
    }, {
      module: 'react-ui-tree.css',
      tree_item_id: 15345345,
      leaf: true
    }, {
      module: 'react-ui-tree.js',
      tree_item_id: 1456456,
      leaf: true
    }, {
      module: 'tree.js',
      tree_item_id: 12342345,
      leaf: true
    }]
  }, {
    module: 'example',
    tree_item_id: 16786784677,
    children: [{
      module: 'app.js',
      tree_item_id: 19574986,
      leaf: true
    }, {
      module: 'app.less',
      tree_item_id: 1895864,
      leaf: true
    }, {
      module: 'index.html',
      tree_item_id: 88008345,
      leaf: true
    }]
  }, {
    module: 'lib',
    tree_item_id: 1345666,
    children: [{
      module: 'node.js',
      tree_item_id: 12377,
      leaf: true
    }, {
      module: 'react-ui-tree.js',
      tree_item_id: 176543332,
      leaf: true
    }, {
      module: 'react-ui-tree.less',
      tree_item_id: 156742,
      leaf: true
    }, {
      module: 'tree.js',
      tree_item_id: 156732,
      leaf: true
    }]
  }, {
    module: '.gitiignore',
    tree_item_id: 16257444,
    leaf: true
  }, {
    module: 'index.js',
    tree_item_id: 144444,
    leaf: true
  }, {
    module: 'LICENSE',
    tree_item_id: 155555,
    leaf: true
  }, {
    module: 'Makefile',
    tree_item_id: 166666,
    leaf: true
  }, {
    module: 'package.json',
    tree_item_id: 1777777,
    leaf: true
  }, {
    module: 'README.md',
    tree_item_id: 188888,
    leaf: true
  }, {
    module: 'webpack.config.js',
    tree_item_id: 199999,
    leaf: true
  }]
}
